### ISSUE TITLE
How to add icon

### ISSUE THREAD

**Issue by sarayd** [hemangsk/Gravity#31]
Hi, 

How would you add icons beside the Github and Twitter you have in the footer? I've downloaded a Facebook icon and converted it to svg and imitated the format for both the svg and html of the github icon, yet it is still not working. Can I ask where you downloaded your svg for Github from?

Thanks!

Here is what the svg for the Facebook icon looks like, and I think somehow it doesn't look right?
d="M51 506 c-45 -25 -50 -49 -51 -244 0 -200 6 -228 55 -250 36 -16 374
-16 410 0 49 22 55 51 55 248 0 197 -6 226 -55 248 -38 17 -382 16 -414 -2z
m369 -115 c0 -25 -4 -30 -27 -33 -22 -2 -29 -9 -31 -30 -3 -25 0 -28 26 -28
26 0 28 -3 24 -30 -3 -24 -9 -30 -28 -30 -24 0 -24 -2 -24 -90 l0 -90 -40 0
-40 0 0 90 c0 73 -3 90 -15 90 -10 0 -15 10 -15 30 0 20 5 30 15 30 11 0 15
11 15 39 0 52 34 81 96 81 42 0 44 -1 44 -29z"
All of these are integers, but yours seems to have floating points

**Comment by hemangsk** [comment]
I am using the svgs provided in the default jekyll theme itself, Can you give a link to the repo so I can see what's wrong?

**Comment by hemangsk** [comment]
ping @sarayd, is there anyway I can help?

**Comment by sarayd** [comment]
@hemangsk hey! very sorry for not following up on this, but I appreciate your very quick reply. Im going to look more into it today and let you know asap!

**Comment by sarayd** [comment]
Here's the [link](https://github.com/sarayd/sarayd.github.io) to my repo. I mainly just want to get an email and Facebook icon in the footer but I'm unsure of how to do that :(

**Comment by flow23** [comment]
Hi, just get the svg files, upload them and  add the html code.

**Comment by hemangsk** [comment]
@sarayd Thats ok I was just wondering if your svg issue resolved or not, (because me too struggle with svgs a lot 😅 ).. 

I googled for facebook svg and there was a svg available on wikipedia which I used here,
https://github.com/hemangsk/sarayd.github.io/blob/master/_includes/icon-facebook.html

So the img tag has,
```height=16```
thats because our old twitter icon has the same height, so to match its height I added height =16.

You'll have to do one more change in footer, to add icons
https://github.com/hemangsk/sarayd.github.io/commit/dcd57e3a92cd182b487cb2e8d5380edcd28f8ed8

**Comment by hemangsk** [comment]
Hey! Please reopen this if issue still persists. :smil
